/*
 * Beta feature flags
 * 新しい機能は FEATURES に追加し、ゲーム側では必ずこの値を確認します。
 * false にすれば UI とロジックをまとめて停止できます。
 */
const FEATURES = Object.freeze({
  titleScreen: true,
  hud: true,
  dialogue: true,
  collectibles: true,
  worldRestoration: true,
  checkpoint: true,
  mobileControls: true,
  particles: true,
  sound: false,
  inventory: false,
  quests: false,
  saveData: true,
  autoSave: true,
  persistentSettings: true,
  debug: false,
  developerTools: true,
  abilitySystem: true,
  orbMagnet: true,
  comboMeter: true,
  speedStreaks: true,
  landingDust: true,
  orbPulse: true,
  orbCompass: true,
  checkpointAura: true,
  enemyEyes: true,
  stageBanner: true,
  courseTips: true,
  windParticles: true,
  playerShadow: true,
  attackArc: true,
  dashAfterimages: true,
  airDashRing: true,
  enemyDirectionMarkers: true,
  checkpointBeam: true,
  repairPulse: true,
  gateSparkles: true,
  dangerVignette: true,
  coyoteJump: true,
  jumpBuffer: true,
  variableJump: true,
  attackLunge: true,
  hitStop: true,
  orbTrail: true,
  repairDust: true,
  goalBeacon: true,
  groundDashReadyHint: true,
  cameraLookAhead: true,
  footstepMemory: true,
  gravityRotation: true,
  enemyPurification: true,
  windPlatforms: true,
  fallAssist: true,
  shadowGuide: true,
  dashPlatforms: true,
  rainStairs: true,
  blueprintWalk: true,
  rhythmPatrol: true,
  timeShift: true,
  todoErase: true,
  rewind: true,
  heightLayer: true,
  bellWave: true,
  rhythmPlatforms: true,
  particleStealth: true,
  orbThrow: true,
  futureWindows: true,
  restoredResidents: true,
  memoryFragments: true,
  dynamicSigns: true,
  idleLore: true,
  restorationEchoes: true,
  bridgeNames: true,
  alternateEnding: true,
  worldMemory: true,
  handDrawnMap: true,
  enemyAbilityCopy: true,
  boundaryExpedition: true,
  orbShield: true,
  dashRefillOnOrb: true,
  checkpointRecall: true,
  groundPound: true,
  repairCombo: true,
  recoveryGlow: true,
  perfectLanding: true,
  enemyStun: true,
  windCatch: true,
  chargeAttack: true,
  doubleJump: true,
  glideFlight: true,
  dashOrbAttract: true,
  attackOrbBurst: true,
  enemyKnockback: true,
  repairShield: true,
  comboTimeSlow: true,
  checkpointWind: true,
  orbBounce: true,
  skyGlyphs: true,
  // Chapter 1 の「集める→直す→進む」を見える形にする演出。OFFでも進行条件は変わりません。
  orbGateFlight: true,
  repairAssembly: true,
  stageFlowHints: true,
  // アイデア実装バッチ 001（Idea #17, #28, #35, #38, #39）
  orbRestorationTint: true,
  enemyColorRecovery: true,
  orbEmbroidery: true,
  paperDangerSense: true,
  ghostConstructionMeteors: true,
  // アイデア実装バッチ 002（Idea #8, #14, #19）
  checkpointFailureChronicle: true,
  patientEnemyPause: true,
  purificationColorRecovery: true,
  // アイデア実装バッチ 003（Idea #5, #12, #29）
  repairSignCompletion: true,
  futureWindowRestoration: true,
  residentLanternTrail: true,
  // アイデア実装バッチ 004（Idea #6）
  constellationBridge: true,
  // アイデア実装バッチ 005（Idea #40, #42）
  distantRestorationIslands: true,
  repairDiscoverySilhouette: true,
  // アイデア実装バッチ 006：修復を「敵を遠ざける選択」と「道の予見」にする。
  repairCalmsEnemies: true,
  purificationGuideTrail: true,
  repairOutcomePreview: true,
  // アイデア実装バッチ 007：連続収集と敵のいた場所を、短い移動の選択に変える。
  orbResonanceSprint: true,
  enemyMemoryStep: true,
  // アイデア実装バッチ 008：所持オーブを一つ使い、進行方向に仮設足場を組む。
  orbBuildPlatform: true,
});

const GAME_CONFIG = Object.freeze({
  width: 1280,
  height: 720,
  gravity: 1700,
  playerSpeed: 340,
  jumpVelocity: 660,
  totalShards: 20,
  initialDialogue: 'ピース「これ……たぶん、まだ途中だよ。修復ポイントのそばで E を押してみよう。」',
  endDialogue: '第1章クリア！ はじまり島に、新しい光がともった。',
});

/*
 * 数値が遊び方を決める仕組み。Stage BuilderはこのキーをそのままJSONに書けます。
 * STAGE_NUMERIC_OVERRIDES の値が、該当ステージだけ下の標準値を上書きします。
 */
const MECHANIC_NUMBERS = Object.freeze({
  footstepCellSize: 180,
  footstepMemoryWindow: 18,
  footstepPlatformWidth: 124,
  footstepPlatformLife: 3.2,
  windSpeed: 1.35,
  windBridgeAmplitude: 22,
  windPlatformAmplitude: 8,
  rhythmPlatformSpeed: 3.2,
  rhythmPlatformAmplitude: 7,
  fallAssistWidth: 150,
  fallAssistLife: 4,
  dashPlatformLife: 1.65,
  rainStairLife: 1.6,
  blueprintLife: 1.2,
  rewindFrames: 70,
  rewindInvulnerability: 0.6,
  gravityMultiplier: 1,
  timeShiftEnemyRate: 0.45,
  timeShiftDuration: 0,
  todoEraseDuration: 3,
  heightLayerY: 220,
  heightLayerSpeedMultiplier: 1.12,
  bellWaveLife: 0.38,
  bellWaveRadius: 115,
  orbThrowSpeed: 640,
  orbThrowGravityMultiplier: 0.65,
  orbThrowLife: 1.1,
  particleStealthMinimum: 0.18,
  shadowGuideDistance: 72,
  orbGateFlightDuration: 0.56,
  repairAssemblyDuration: 0.72,
  airDashDuration: 0.18,
  patientEnemyWatchTime: 1.7,
  patientEnemyPauseTime: 2.4,
  constellationBridgeOrbs: 3,
  constellationBridgeLife: 2.8,
  repairDiscoveryDistance: 260,
  repairCalmRadius: 250,
  repairCalmDuration: 3.6,
  purificationGuideLife: 3.2,
  repairPreviewDistance: 330,
  orbResonanceWindow: 1.35,
  orbResonanceSpeedMultiplier: 1.22,
  orbResonanceDuration: 1.8,
  enemyMemoryStepLife: 1.45,
  orbBuildDelay: 0.3,
  orbBuildPlatformLife: 3.1,
});

const STAGE_NUMERIC_OVERRIDES = Object.freeze({
  1: { windPlatformAmplitude: 3, rhythmPlatformAmplitude: 0 },
  2: { windPlatformAmplitude: 7, rhythmPlatformAmplitude: 2 },
  3: { windPlatformAmplitude: 12, rhythmPlatformAmplitude: 4 },
  4: { windPlatformAmplitude: 5, rhythmPlatformAmplitude: 1 },
  5: { windPlatformAmplitude: 16, dashPlatformLife: 2.1, rainStairLife: 2.0 },
  6: { windPlatformAmplitude: 7, rhythmPlatformAmplitude: 5 },
  7: { windPlatformAmplitude: 10, rhythmPlatformAmplitude: 2 },
  8: { windPlatformAmplitude: 7, rhythmPlatformAmplitude: 5 },
  9: { windPlatformAmplitude: 4, rhythmPlatformAmplitude: 7 },
  10: { windBridgeAmplitude: 30, rhythmPlatformAmplitude: 10 },
  11: { windPlatformAmplitude: 8, rhythmPlatformAmplitude: 3 },
  12: { windPlatformAmplitude: 13, rhythmPlatformAmplitude: 6 },
  13: { windPlatformAmplitude: 0, rhythmPlatformAmplitude: 0, footstepPlatformLife: 4.4 },
});

/* ステージごとの物語素材。画像を増やさず、個別の位置・台詞・未来の景色を設定できます。 */
const NARRATIVE_STAGE_CONTENT = Object.freeze({
  1:{ window:[1110,280], fragment:[1520,340], sign:'TODO: はじまりの足場を固定する', resident:'橋ができた！　これで、次の島に道が続くよ。', memory:'設計者の走り書き：最初の一歩は、未完成でも足場になる。' },
  2:{ window:[1360,250], fragment:[1860,310], sign:'雲裂き工区／風圧の値：未入力', resident:'風は怖くないよ。進む方向を教えてくれるから。', memory:'誰かのメモ：雲は壊れない。形を変えるだけだ。' },
  3:{ window:[1640,210], fragment:[2120,300], sign:'宙吊り回廊／安全確認：途中', resident:'上を見て。壊れた空にも、ちゃんと道がある。', memory:'古い記録：重力は、世界を下へ引く約束だった。' },
  4:{ window:[1750,265], fragment:[2300,330], sign:'採掘路／採掘物：記憶の結晶', resident:'掘り出したのは石じゃない。忘れられた景色だよ。', memory:'設計図の隅：失くした物にも、帰る場所を作ろう。' },
  5:{ window:[1640,160], fragment:[2260,220], sign:'縦坑／空中移動：試験運用中', resident:'空で一度だけ、強く踏み出して。風が受け止める。', memory:'Solの記録：飛べない日にも、空は待ってくれる。' },
  6:{ window:[1800,210], fragment:[2510,260], sign:'結晶庭／月光の屈折を調整中', resident:'結晶は、見てくれた光をずっと覚えている。', memory:'庭師の言葉：欠けた光も、花を咲かせられる。' },
  7:{ window:[2080,230], fragment:[2800,290], sign:'連橋／夜間工事：継続中', resident:'暗い橋ほど、手すりの光がきれいに見える。', memory:'夜番の日誌：渡る人がいる限り、橋は完成し続ける。' },
  8:{ window:[2130,180], fragment:[2980,250], sign:'尖塔／外壁の時間風化を観測', resident:'古い傷は、ここまで来た証でもあるんだ。', memory:'塔の銘文：遠くを見るために、高くなる必要はない。' },
  9:{ window:[2240,220], fragment:[3100,270], sign:'氷雲足場／低温注意', resident:'凍った雲でも、ちゃんと温かい思い出が眠ってる。', memory:'小さな手紙：春は、氷の内側から始まる。' },
  10:{ window:[2280,180], fragment:[3260,250], sign:'熔岩雲／熱量制御：警告', resident:'熱い場所ほど、直す手はゆっくりでいい。', memory:'鍛冶師の言葉：火は壊すためだけに燃えていない。' },
  11:{ window:[2440,200], fragment:[3390,260], sign:'落下遺跡／復元順序を探索中', resident:'落ちた物を全部拾わなくても、前へ進める。', memory:'遺跡の声：崩れた順番には、守りたかった理由がある。' },
  12:{ window:[2520,165], fragment:[3520,240], sign:'外縁／星喰いの影を記録', resident:'外の暗さを知っているから、島の光は強いんだ。', memory:'航海記：終わりに見える場所も、地図の余白だった。' },
  13:{ window:[2600,180], fragment:[3700,240], sign:'最終工区／完成度：あと少し', resident:'ここまで直した世界は、もう君のことを覚えている。', memory:'最後の記録：完璧じゃなくても、ここは世界になった。' },
});
